In [1]:
# Load data
import pandas as pd

data = pd.read_csv('editors.csv')
test = pd.read_csv('test.csv')

In [2]:
features = ['Pclass', 'Age', 'Sex_binary', 'SibSp', 'Parch']
target = 'Survived'

In [3]:
data.head()

   Surname         First Names  Age      Boarded Class Body Number
0   Abbing          Mr Anthony   42  Southampton   3rd           –
1   Abbott  Mr Rossmore Edward   16  Southampton   3rd        #190
2   Abbott    Mr Eugene Joseph   14  Southampton   3rd           –
3  Abelson           Mr Samuel   30    Cherbourg   2nd           –
4    Ådahl          Mr Mauritz   30  Southampton   3rd         #72

In [17]:
Y_predicted = []

for index, row in test.iterrows():
    string = row.Name.split(', ')[0]
    # string = string.replace('.', '')
    print(sum(data['Surname'] == string))
    # print(data['First Names'][0])
    # data['First Names'] == row.Name]

0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
4
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
2
0
0
1
3
0
0
0
1
0
1
0
0
1
0
0
0
0
0
0
3
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
4
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
4
1
0
0
0
1
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
2
0
0
0
0
0
1
0
0
0
9
0
0
0
0
0
0
0
1
0
0
0
4
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
3
0
0
0
4
0
0
1
0
0
0
0
0
0
9
0
0
0
0
1
0
0
2
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
1
0
1
0
4
0
0
0
0
0
0
1
1
2
0
0
0
2
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [5]:
submission = pd.DataFrame({'PassengerId':test['PassengerId'],'Survived':Y_predicted})
submission.head(5)

ValueError: array length 0 does not match index length 418

In [14]:
filename = 'titanic-predictions-1.csv'

submission.to_csv(filename, index=False)

print('Saved file: ' + filename)

Saved file: titanic-predictions-1.csv